import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptorsFromDi, HTTP_INTERCEPTORS } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideIcons } from '@ng-icons/core';
import {
  lucideAlertCircle,
  lucideArrowLeft,
  lucideBan,
  lucideBarChart3,
  lucideBell,
  lucideBellOff,
  lucideCalendarDays,
  lucideCalendarOff,
  lucideCheckCircle,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronUp,
  lucideCircleAlert,
  lucideCircleStop,
  lucideClock,
  lucideEllipsis,
  lucideEye,
  lucideEyeOff,
  lucideFileText,
  lucideGitBranchPlus,
  lucideHelpCircle,
  lucideInbox,
  lucideKey,
  lucideLayoutDashboard,
  lucideList,
  lucideLock,
  lucideLogOut,
  lucideMail,
  lucideMap,
  lucideMoon,
  lucideMapPin,
  lucideMapPinOff,
  lucideMenu,
  lucidePencil,
  lucidePlus,
  lucideRefreshCw,
  lucideSearch,
  lucideSettings,
  lucideShieldAlert,
  lucideSlash,
  lucideSun,
  lucideTable,
  lucideTimer,
  lucideTrash2,
  lucideTriangleAlert,
  lucideUser,
  lucideUserX,
  lucideUsers,
  lucideX,
} from '@ng-icons/lucide';
import { routes } from './app.routes';
import { JwtInterceptor } from './core/auth/jwt.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptorsFromDi()),
    provideAnimations(),
    { provide: HTTP_INTERCEPTORS, useClass: JwtInterceptor, multi: true },
    provideIcons({
      lucideAlertCircle,
      lucideArrowLeft,
      lucideBan,
      lucideBarChart3,
      lucideBell,
      lucideBellOff,
      lucideCalendarDays,
      lucideCalendarOff,
      lucideCheckCircle,
      lucideChevronDown,
      lucideChevronLeft,
      lucideChevronRight,
      lucideChevronUp,
      lucideCircleAlert,
      lucideCircleStop,
      lucideClock,
      lucideEllipsis,
      lucideEye,
      lucideEyeOff,
      lucideFileText,
      lucideGitBranchPlus,
      lucideHelpCircle,
      lucideInbox,
      lucideKey,
      lucideLayoutDashboard,
      lucideList,
      lucideLock,
      lucideLogOut,
      lucideMail,
      lucideMap,
      lucideMoon,
      lucideMapPin,
      lucideMapPinOff,
      lucideMenu,
      lucidePencil,
      lucidePlus,
      lucideRefreshCw,
      lucideSearch,
      lucideSettings,
      lucideShieldAlert,
      lucideSlash,
      lucideSun,
      lucideTable,
      lucideTimer,
      lucideTrash2,
      lucideTriangleAlert,
      lucideUser,
      lucideUserX,
      lucideUsers,
      lucideX,
    }),
  ],
};
